#!/usr/bin/env bash
# a script that installs nginx and configures index.html
apt update -y && sudo apt install -y nginx &&
    mkdir -p /var/www/html/ &&
    echo "Holberton School" | tee /var/www/html/index.html &&
    newtext="rewrite ^/redirect_me https://www.youtube.com/watch?v=jyknCVczn3Q permanent;"
sed -i "/listen 80 default_server/a $newtext" /etc/nginx/sites-available/default &&
    sudo ufw allow 'Nginx HTTP'
    service nginx start
