#!/usr/bin/env bash
# a script that installs nginx, configures index.html, and other edits
sudo apt update -y && sudo apt install -y nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
newtext="rewrite ^/redirect_me https://www.youtube.com/watch?v=jyknCVczn3Q permanent;"
sed -i "/listen 80 default_server/a $newtext" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /var/www/html;\n internal;}' /etc/nginx/sites-available/default
service nginx start
