#!/usr/bin/env bash
# a script that installs nginx and configures index.html
apt update -y && sudo apt install -y nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
re_text="rewrite ^/redirect_me https://www.youtube.com/watch?v=jyknCVczn3Q permanent;"
h_text="add_header X-Served-By $HOSTNAME;"
err_text="error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}"
sed -i "/listen 80 default_server/a $re_text\n\t$h_text\n\t$err_text" /etc/nginx/sites-available/default
service nginx start
