#!/usr/bin/env bash
# a script that installs nginx and configures index.html
apt update -y && sudo apt install -y nginx
echo "Holberton School" > /var/www/html/index.html
re_text="rewrite ^/redirect_me https://www.youtube.com/watch?v=jyknCVczn3Q permanent;"
h_text="add_header X-Served-By $HOSTNAME"
sed -i "/listen 80 default_server/a \t$re_text\n\t$h_text" /etc/nginx/sites-available/default
service nginx start
