#!/usr/bin/env bash
# a script that installs and configures HAproxy
apt-get install -y software-properties-common &&
    add-apt-repository ppa:vbernat/haproxy-2.0 &&
    apt-get update -y &&
    apt-get install -y haproxy=2.0.\*
lb_config="backend web-backend\n\tbalance roundrobin\n\tserver 675-web-01 35.231.178.39:80 check\n\tserver 675-web-02 34.73.236.42:80 check\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend"
echo "$lb_config" >> /etc/haproxy/haproxy.cfg
service haproxy restart
