#!/usr/bin/env bash
# a Bash script that generates a MySQL dump and creates a compressed archive

mysqldump --all-databases -u root -p "$1" > sqlbackup
tar -zcvf "$(date '+%d-%m-%Y').tar.gz" sqlbackup
rm sqlbackup
