#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd.

IFS=':'
while read one two three four five six seven; do
    printf "The user %s is part of the %s gang, lives in \
%s and rides %s. %s's place is protected by \
the passcode %s, more info about the user here: %s\n"\
	   "$one" "$four" "$six" "$seven" "$three" "$two" "$five"
done < /etc/passwd
