#!/usr/bin/env bash
# a Bash script that displays Holberton School 10 times, but for the 9th
# iteration, displays Holberton School and then Hi on a new line.

i=0

while ((i < 10)); do
    if ((i == 8)); then
	echo "Hi"
    else
    echo "Holberton School"
    fi
    ((i++))
done
