#!/usr/bin/env bash
# a Bash script that displays Holberton School 10 times, but for the 9th
# iteration, displays Holberton School and then Hi on a new line.

i=1
while ((i <= 20)); do
    echo $i
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((i++))
done
