#!/usr/bin/env bash
# a Bash script that displays Holberton School 10 times, but for the 9th
# iteration, displays Holberton School and then Hi on a new line.

i=1
while ((i <= 20)); do
    echo $i
    if ((i == 4)); then
	echo "bad luck from China"
    elif ((i == 9)); then
	echo "bad luck from Japan"
    elif ((i == 17)); then
	echo "bad luck from Italy"
    fi
    ((i++))
done
