#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes 

minute=1
hour=0
while ((hour <= 12)); do
    echo "Hour: $hour"
    while  ((minute<= 59)); do
    	echo $minute
    	((minute++))
    done
    ((hour++))
    minute=1
done
