#!/usr/bin/env bash
# a script that configures an Ubuntu server with new network requirements
sudo cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
